name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get required packages
      run: sudo apt-get update && sudo apt-get install libdbus-1-dev
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Clippy lints
      run: cargo clippy --all-features --all-targets
    - name: Build all features (release)
      run: cargo build --all-features --all-targets --verbose --release
    - name: Run tests
      run: cargo test --all-features --all-targets --verbose
